# Generated by Django 4.2.4 on 2023-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('workout', models.CharField(max_length=200)),
                ('trained_by', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
